// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30g5VcxcbpEMG5nWa41X0hlciQ82J_SY',
    appId: '1:15037414348:web:37300581901ce3d28d3b69',
    messagingSenderId: '15037414348',
    projectId: 'pdp-t-9d91b',
    authDomain: 'pdp-t-9d91b.firebaseapp.com',
    databaseURL: 'https://pdp-t-9d91b-default-rtdb.firebaseio.com',
    storageBucket: 'pdp-t-9d91b.appspot.com',
    measurementId: 'G-J8DCC3JW7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvU8w-FICnMuqdds9M9sl0GHt0CiCEI7w',
    appId: '1:15037414348:android:19e165efd7b47c858d3b69',
    messagingSenderId: '15037414348',
    projectId: 'pdp-t-9d91b',
    databaseURL: 'https://pdp-t-9d91b-default-rtdb.firebaseio.com',
    storageBucket: 'pdp-t-9d91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNVbhm2sIhgoOyUSyk_XSQeWhMXTxXH4',
    appId: '1:15037414348:ios:9f20d8cf5d865f138d3b69',
    messagingSenderId: '15037414348',
    projectId: 'pdp-t-9d91b',
    databaseURL: 'https://pdp-t-9d91b-default-rtdb.firebaseio.com',
    storageBucket: 'pdp-t-9d91b.appspot.com',
    iosClientId: '15037414348-mfs4ico4b0vpck2u3mo3jmfigaqs777v.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdpTcg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiNVbhm2sIhgoOyUSyk_XSQeWhMXTxXH4',
    appId: '1:15037414348:ios:9f20d8cf5d865f138d3b69',
    messagingSenderId: '15037414348',
    projectId: 'pdp-t-9d91b',
    databaseURL: 'https://pdp-t-9d91b-default-rtdb.firebaseio.com',
    storageBucket: 'pdp-t-9d91b.appspot.com',
    iosClientId: '15037414348-mfs4ico4b0vpck2u3mo3jmfigaqs777v.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdpTcg',
  );
}
